//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBFetchData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\v11.0;Initial Catalog=E:\\FINANCE\\DATABASE\\OPTIONS.MDF;Integ" +
            "rated Security=True")]
        public string E__FINANCE_DATABASE_OPTIONS_MDFConnectionString {
            get {
                return ((string)(this["E__FINANCE_DATABASE_OPTIONS_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>50</string>
  <string>158</string>
  <string>76</string>
  <string>159</string>
  <string>70</string>
  <string>70</string>
  <string>70</string>
  <string>70</string>
  <string>60</string>
  <string>60</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CompanyInfoColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CompanyInfoColumnWidths"]));
            }
            set {
                this["CompanyInfoColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>50</string>
  <string>158</string>
  <string>76</string>
  <string>159</string>
  <string>70</string>
  <string>70</string>
  <string>70</string>
  <string>70</string>
  <string>60</string>
  <string>60</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StockAnalColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StockAnalColumnWidths"]));
            }
            set {
                this["StockAnalColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>50</string>
  <string>158</string>
  <string>76</string>
  <string>159</string>
  <string>70</string>
  <string>70</string>
  <string>70</string>
  <string>70</string>
  <string>60</string>
  <string>60</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OptionAnalColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OptionAnalColumnWidths"]));
            }
            set {
                this["OptionAnalColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Finance\\logs\\")]
        public string OptionFolder {
            get {
                return ((string)(this["OptionFolder"]));
            }
            set {
                this["OptionFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int AnalMinVolume {
            get {
                return ((int)(this["AnalMinVolume"]));
            }
            set {
                this["AnalMinVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AnalMinPrice {
            get {
                return ((int)(this["AnalMinPrice"]));
            }
            set {
                this["AnalMinPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double AnalMinIVPercentile {
            get {
                return ((double)(this["AnalMinIVPercentile"]));
            }
            set {
                this["AnalMinIVPercentile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-08-22")]
        public global::System.DateTime AnalNixEarnings {
            get {
                return ((global::System.DateTime)(this["AnalNixEarnings"]));
            }
            set {
                this["AnalNixEarnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectTWS {
            get {
                return ((bool)(this["ConnectTWS"]));
            }
            set {
                this["ConnectTWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ClientID {
            get {
                return ((int)(this["ClientID"]));
            }
            set {
                this["ClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>150</string>
  <string>150</string>
  <string>150</string>
  <string>150</string>
  <string>150</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BBColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BBColumnWidths"]));
            }
            set {
                this["BBColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>100</string>
  <string>100</string>
  <string>100</string>
  <string>100</string>
  <string>100</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HistoricalBBColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HistoricalBBColumnWidths"]));
            }
            set {
                this["HistoricalBBColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bAnalOptPuts {
            get {
                return ((bool)(this["bAnalOptPuts"]));
            }
            set {
                this["bAnalOptPuts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAnalOptCalls {
            get {
                return ((bool)(this["bAnalOptCalls"]));
            }
            set {
                this["bAnalOptCalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAnalOptOIThreshold {
            get {
                return ((bool)(this["bAnalOptOIThreshold"]));
            }
            set {
                this["bAnalOptOIThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAnalOptROCThreshold {
            get {
                return ((bool)(this["bAnalOptROCThreshold"]));
            }
            set {
                this["bAnalOptROCThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAnalOptMinPremium {
            get {
                return ((bool)(this["bAnalOptMinPremium"]));
            }
            set {
                this["bAnalOptMinPremium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bAnalOptUseFrozen {
            get {
                return ((bool)(this["bAnalOptUseFrozen"]));
            }
            set {
                this["bAnalOptUseFrozen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAnalOptStrangleThreshold {
            get {
                return ((bool)(this["bAnalOptStrangleThreshold"]));
            }
            set {
                this["bAnalOptStrangleThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15%")]
        public string AnalOptITMThreshold {
            get {
                return ((string)(this["AnalOptITMThreshold"]));
            }
            set {
                this["AnalOptITMThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AnalOptOIThreshold {
            get {
                return ((int)(this["AnalOptOIThreshold"]));
            }
            set {
                this["AnalOptOIThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5%")]
        public string AnalOptROCThreshold {
            get {
                return ((string)(this["AnalOptROCThreshold"]));
            }
            set {
                this["AnalOptROCThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$1.00")]
        public string AnalOptMinPremium {
            get {
                return ((string)(this["AnalOptMinPremium"]));
            }
            set {
                this["AnalOptMinPremium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>50</string>\r\n  <string>50</string>\r\n  <string />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IVPercentileColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IVPercentileColumnWidths"]));
            }
            set {
                this["IVPercentileColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PortfolioIndex {
            get {
                return ((int)(this["PortfolioIndex"]));
            }
            set {
                this["PortfolioIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Finance\\Logs\\")]
        public string LogDir {
            get {
                return ((string)(this["LogDir"]));
            }
            set {
                this["LogDir"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=E:\\Finance\\Database\\options.mdf;Inte" +
            "grated Security=True;Connect Timeout=30")]
        public string optionsConnectionString {
            get {
                return ((string)(this["optionsConnectionString"]));
            }
        }
    }
}
